"""Custom loss functions for standard and advanced GAN training."""

import torch
import torch.nn as nn

def get_adversarial_loss():
    """
    Returns the standard binary cross-entropy loss function used for GANs.
    Using BCEWithLogitsLoss is numerically more stable than using a Sigmoid 
    layer followed by BCELoss.
    """
    return nn.BCEWithLogitsLoss()

def custom_adversarial_loss(g_fake, target_model, lambda_weight=0.1):
    """
    Calculates the advanced custom loss for the Generator, incorporating 
    feedback from the target (victim) model.
    
    Args:
        g_fake (Tensor): The fake images generated by the Generator (6, C, H, W).
        target_model (nn.Module): The victim model we are trying to fool.
        lambda_weight (float): How much weight to give the target model's loss 
                               relative to the standard GAN loss.
                               
    Returns:
        Tensor: The calculated classification loss penalty.
    """
    if target_model is None:
        return torch.tensor(0.0, device=g_fake.device)
        
    # We want the target model to classify the fake images as '0' (Genuine/Real)
    # Assuming target_model outputs a single logit where 0 is Genuine, 1 is Counterfeit
    
    # We detach the target model so we don't accidentally train it
    target_model.eval()
    for param in target_model.parameters():
        param.requires_grad = False
        
    target_logits = target_model(g_fake)
    
    # Target is 0 (Genuine). We use BCEWithLogitsLoss.
    target_labels = torch.zeros_like(target_logits, device=g_fake.device)
    loss_fn = nn.BCEWithLogitsLoss()
    
    classification_loss = loss_fn(target_logits, target_labels)
    
    return lambda_weight * classification_loss
