"""Architecture A: Multi-Layer Perceptron (MLP) GAN (Baseline)."""

import torch
import torch.nn as nn
import numpy as np

class MLPGenerator(nn.Module):
    """
    Generator for the baseline MLP GAN.
    
    This model takes a random latent vector (noise) and passes it through
    a series of fully connected (Dense) layers. The final output is a massive
    flattened array that is reshaped back into the expected 6-segment banknote tensor.
    
    Because it uses fully connected layers, it does not inherently understand
    spatial relationships (2D structures), making it a weak baseline for 
    generating high-resolution adversarial examples.
    """
    def __init__(self, latent_dim=100, img_shape=(6, 3, 256, 256)):
        """
        Args:
            latent_dim (int): Size of the input random noise vector 'z'.
            img_shape (tuple): The expected shape of the output tensor 
                               (Segments, Channels, Height, Width).
        """
        super(MLPGenerator, self).__init__()
        self.latent_dim = latent_dim
        self.img_shape = img_shape
        self.output_dim = int(np.prod(img_shape))

        def block(in_feat, out_feat, normalize=True):
            layers = [nn.Linear(in_feat, out_feat)]
            if normalize:
                layers.append(nn.BatchNorm1d(out_feat, 0.8))
            layers.append(nn.LeakyReLU(0.2, inplace=True))
            return layers

        self.model = nn.Sequential(
            *block(latent_dim, 128, normalize=False),
            *block(128, 256),
            *block(256, 512),
            *block(512, 1024),
            nn.Linear(1024, self.output_dim),
            nn.Tanh() # Outputs values in [-1, 1]
        )

    def forward(self, z):
        """
        Forward pass of the Generator.
        
        Args:
            z (Tensor): Random noise vector of shape (batch_size, latent_dim).
            
        Returns:
            Tensor: Generated fake images of shape (batch_size, 6, C, H, W).
        """
        # z shape: (batch_size, latent_dim)
        img_flat = self.model(z)
        # Reshape to (batch_size, 6, C, H, W)
        img = img_flat.view(img_flat.size(0), *self.img_shape)
        return img


class MLPDiscriminator(nn.Module):
    """
    Discriminator for the baseline MLP GAN.
    
    This model acts as a classifier that tries to distinguish between real 
    banknote tensors and fake ones generated by the MLPGenerator. It flattens
    the 6-segment input tensor into a 1D array and processes it through 
    fully connected layers with Dropout for regularization.
    """
    def __init__(self, img_shape=(6, 3, 256, 256)):
        """
        Args:
            img_shape (tuple): The expected shape of the input tensor 
                               (Segments, Channels, Height, Width).
        """
        super(MLPDiscriminator, self).__init__()
        self.img_shape = img_shape
        self.input_dim = int(np.prod(img_shape))

        self.model = nn.Sequential(
            nn.Linear(self.input_dim, 512),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Dropout(0.3),
            nn.Linear(512, 256),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Dropout(0.3),
            nn.Linear(256, 1)
            # No Sigmoid here; we will use BCEWithLogitsLoss during training for better stability
        )

    def forward(self, img):
        """
        Forward pass of the Discriminator.
        
        Args:
            img (Tensor): Real or fake images of shape (batch_size, 6, C, H, W).
            
        Returns:
            Tensor: A single logit per image predicting real vs. fake.
        """
        # img shape: (batch_size, 6, C, H, W)
        img_flat = img.view(img.size(0), -1)
        validity = self.model(img_flat)
        return validity
